// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces fieldsfirst safe 
// Source File Name:   ArtifactList.java

package com.middleearthgames.orderchecker;

import com.middleearthgames.orderchecker.io.Data;
import java.util.Vector;

// Referenced classes of package com.middleearthgames.orderchecker:
//            Artifact, Main

class ArtifactList
{

    private Vector artifacts;

    ArtifactList()
    {
        artifacts = new Vector();
        configureList();
    }

    Artifact findArtifact(int artifactNum)
    {
        int gameType = Main.main.getData().getGameType();
        if(gameType != 1 && gameType != 0)
        {
            return null;
        }
        for(int i = 0; i < artifacts.size(); i++)
        {
            Artifact artifact = (Artifact)artifacts.get(i);
            if(artifact.getArtifactNumber() == artifactNum && artifact.getGame() == gameType)
            {
                return artifact;
            }
        }

        return null;
    }

    private void configureList()
    {
        artifacts.add(((Object) (new Artifact(1, "Ring of Wind", 1, 0, "+40 Agent"))));
        artifacts.add(((Object) (new Artifact(2, "Ring of Stargazing", 1, 0, "+25 Mage"))));
        artifacts.add(((Object) (new Artifact(3, "Ring of Iron Magic", 1, 1, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(4, "Ring of Impersonation", 1, 0, "+25 Agent"))));
        artifacts.add(((Object) (new Artifact(5, "Ring of Barahir", 1, 2, "+35 Command,Bonus vs Dragons"))));
        artifacts.add(((Object) (new Artifact(6, "Ring of Axardil", 1, 0, "+10 Command,Teleport"))));
        artifacts.add(((Object) (new Artifact(7, "Nazguaga", 1, 1, "+30 Mage,Dark Summons List"))));
        artifacts.add(((Object) (new Artifact(8, "Lorgl\356n", 1, 0, "+15 Mage"))));
        artifacts.add(((Object) (new Artifact(9, "Elenya", 1, 0, "+15 Stealth"))));
        artifacts.add(((Object) (new Artifact(10, "W\364lor Priest Ring", 1, 0, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(11, "Vilya", 1, 0, "+50 Mage"))));
        artifacts.add(((Object) (new Artifact(12, "Nenya", 1, 0, "+50 Mage"))));
        artifacts.add(((Object) (new Artifact(13, "Narya", 1, 0, "+50 Mage"))));
        artifacts.add(((Object) (new Artifact(14, "The One Ring", 1, 0, "+40 Stealth"))));
        artifacts.add(((Object) (new Artifact(15, "Tinculin", 1, 0, "+40 Mage,Spirits Mastery List"))));
        artifacts.add(((Object) (new Artifact(16, "Mothras", 1, 0, "+500 Combat,Random Lost List"))));
        artifacts.add(((Object) (new Artifact(17, "Ring of Angrenost", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(18, "Tablets of Dark Knowledge", 1, 1, "+15 Mage,Random Lost List"))));
        artifacts.add(((Object) (new Artifact(19, "Staff of Storms", 1, 0, "Open Seas,Dark Summons List"))));
        artifacts.add(((Object) (new Artifact(20, "Staff of the Serpent", 1, 0, "+10 Mage"))));
        artifacts.add(((Object) (new Artifact(21, "Staff of Earthmastery", 1, 0, "+20 Mage,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(22, "Rauzgnagli", 1, 1, "+1750 Combat"))));
        artifacts.add(((Object) (new Artifact(23, "Nedelhach", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(24, "Ghostbane", 1, 0, "+750 Combat,Bonus vs Undead"))));
        artifacts.add(((Object) (new Artifact(25, "Staff of Bronze", 1, 0, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(26, "Mallorn Staff", 1, 0, "+25 Mage"))));
        artifacts.add(((Object) (new Artifact(27, "Palantir of Osgiliath", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(28, "Palantir of Minas Ithil", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(29, "Palantir of Minas Anor", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(30, "Palantir of Orthanc", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(31, "Palant\355r of Ann\372minas", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(32, "Palantir of Elostirion", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(33, "Palant\355r of Amon S\373l", 1, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(34, "Orb of Dark Seeing", 1, 1, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(35, "Orb of Seeing", 1, 0, "+35 Mage"))));
        artifacts.add(((Object) (new Artifact(36, "Bone Ring", 1, 0, "+15 Mage"))));
        artifacts.add(((Object) (new Artifact(37, "Voice of the Dark Tower", 1, 1, "+20 Emissary"))));
        artifacts.add(((Object) (new Artifact(38, "Silver Rod of Ad\372ni", 1, 2, "+25 Command"))));
        artifacts.add(((Object) (new Artifact(39, "Miramarth", 1, 1, "+15 Agent"))));
        artifacts.add(((Object) (new Artifact(40, "Gaergil", 1, 0, "Open Seas"))));
        artifacts.add(((Object) (new Artifact(41, "Mantle of Doriath", 1, 2, "Hide Pop Center"))));
        artifacts.add(((Object) (new Artifact(42, "Collar of Might", 1, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(43, "Cloak of the Heavens", 1, 0, "+15 Agent"))));
        artifacts.add(((Object) (new Artifact(44, "Collohwesta", 1, 0, "+25 Stealth"))));
        artifacts.add(((Object) (new Artifact(45, "Cloak of the Abyss", 1, 0, "+40 Stealth"))));
        artifacts.add(((Object) (new Artifact(46, "Robes of the Orc Priests", 1, 1, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(47, "Belt of Durin", 1, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(48, "Th\364logaer Ciryatano", 1, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(49, "Shield of An\341rion", 1, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(50, "Ovir Crown", 1, 0, "+15 Mage"))));
        artifacts.add(((Object) (new Artifact(51, "Ossanna", 1, 0, "+10 Mage"))));
        artifacts.add(((Object) (new Artifact(52, "Morgul Plate", 1, 1, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(53, "Listening Helm", 1, 0, "+10 Agent"))));
        artifacts.add(((Object) (new Artifact(54, "Helm of Sen Jay", 1, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(55, "Helm of Shadow", 1, 0, "+10 Stealth"))));
        artifacts.add(((Object) (new Artifact(56, "Helm of the Mumak-King", 1, 0, "+25 Command,Bonus Recruit/Fight Mumaks"))));
        artifacts.add(((Object) (new Artifact(57, "Helm of Isildur", 1, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(58, "Helm of the Dark", 1, 1, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(59, "Gaerennon", 1, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(60, "Durin's Armor and Shield", 1, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(61, "Dragon Helm of Dor-L\363min", 1, 2, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(62, "Dragon Helm and Armor", 1, 1, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(63, "Deepwood Bracelet", 1, 0, "+10 Mage"))));
        artifacts.add(((Object) (new Artifact(64, "Bracers of the Mist", 1, 0, "+30 Stealth"))));
        artifacts.add(((Object) (new Artifact(65, "Angbor", 1, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(66, "Bracers of Chennacatt", 1, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(67, "Ul\373kai", 1, 1, "+35 Command"))));
        artifacts.add(((Object) (new Artifact(68, "Thrakurghash", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(69, "Corantir", 1, 0, "+10 Mage"))));
        artifacts.add(((Object) (new Artifact(70, "Ring of Binding", 1, 1, "+25 Agent"))));
        artifacts.add(((Object) (new Artifact(71, "Talisman of Absorption", 1, 1, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(72, "Cloak of Duvorn", 1, 0, "+20 Agent"))));
        artifacts.add(((Object) (new Artifact(73, "Yellow Hammer", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(74, "War-dancer", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(75, "Vasamacil", 1, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(76, "Usriev", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(77, "Ungolrist", 1, 2, "+750 Combat,Bonus vs Spiders"))));
        artifacts.add(((Object) (new Artifact(78, "Sword of Soul Reducing", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(79, "Stormless Bow", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(80, "Snow Hammer", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(81, "Sil-Maegil", 1, 2, "+750 Combat,Bonus vs Evil Creatures"))));
        artifacts.add(((Object) (new Artifact(82, "Romoquen\341ro", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(83, "Orcrist", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(84, "Ongrum", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(85, "Navorn", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(86, "Nallagurth", 1, 1, "+750 Combat,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(87, "Morlhach", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(88, "Macirill\353", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(89, "Macilr\363men", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(90, "Helkaluin", 1, 2, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(91, "Gordur", 1, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(92, "Horse-tamer", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(93, "Gurthdur", 1, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(94, "Glamdring", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(95, "Gildagor", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(96, "Fohnrad", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(97, "Fire's Edge", 1, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(98, "Elhach", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(99, "Elfhewer", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(100, "Elfbane", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(101, "E Voronw\353", 1, 2, "+500 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(102, "Durin's Axe", 1, 0, "+750 Combat,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(103, "Durcrist", 1, 2, "+500 Combat,Perceive Nationality"))));
        artifacts.add(((Object) (new Artifact(104, "Dawnsword", 1, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(105, "Culok", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(106, "Cubragol", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(107, "Curaran", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(108, "Craig-olf-Ti", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(109, "Cloud Bow", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(110, "Cirmegil", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(111, "Believer's Bane", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(112, "Burning Blade", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(113, "Ar-sil", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(114, "Angian", 1, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(115, "Fire Mace", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(116, "Blood Spike", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(117, "Hatred Curse", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(118, "Skull Flail", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(119, "Moon-axe", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(120, "Amulet of Sea Mastery", 1, 0, "Open Seas"))));
        artifacts.add(((Object) (new Artifact(121, "Troll Slayer", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(122, "Orc Slayer", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(123, "Wood-shadow", 1, 0, "+15 Stealth"))));
        artifacts.add(((Object) (new Artifact(124, "Robes of Aman", 1, 2, "+25 Stealth"))));
        artifacts.add(((Object) (new Artifact(125, "Aeglin", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(126, "Anarmacil", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(127, "Aranr\373th", 1, 2, "+1750 Combat,Bonus vs Evil Creatures"))));
        artifacts.add(((Object) (new Artifact(128, "Aratocam", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(129, "Bow of Thunder and Bone", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(130, "Br\364dic Spear", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(131, "Caranlhach", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(132, "Daeron's Rapier", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(133, "Dagger of Green Wisdom", 1, 0, "+500 Combat,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(134, "Dagnirdraug", 1, 2, "+750 Combat,Bonus vs Wolves"))));
        artifacts.add(((Object) (new Artifact(135, "Elenr\373th", 1, 0, "+750 Combat,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(136, "Foam Cleaver", 1, 0, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(137, "Bloodrunner", 1, 0, "+750 Combat,Major Heal"))));
        artifacts.add(((Object) (new Artifact(138, "Air-cleaver", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(139, "Gersebroc", 1, 2, "+750 Combat,Bonus vs Dragons/Fell Beasts"))));
        artifacts.add(((Object) (new Artifact(140, "Red Robes", 1, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(141, "Hue Changer", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(142, "Kirrauko", 1, 2, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(143, "Night-piercer", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(144, "Orcring", 1, 2, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(145, "Orcruin", 1, 2, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(146, "Horse-slayer", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(147, "Ringil", 1, 2, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(148, "Sickle of the Heavens", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(149, "Sting", 1, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(150, "Stinging Tongue", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(151, "Troll-Cleaver", 1, 0, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(152, "Turantir", 1, 2, "+500 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(153, "Water-skimmer", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(154, "Ring of Bleeding", 1, 1, "+25 Mage"))));
        artifacts.add(((Object) (new Artifact(155, "Taurin", 1, 0, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(156, "Maranya", 1, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(157, "Pectoral", 1, 0, "+30 Emissary"))));
        artifacts.add(((Object) (new Artifact(158, "Thunder's Edge", 1, 1, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(159, "Skull Helm", 1, 1, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(160, "Collar of Command", 1, 0, "+30 Command"))));
        artifacts.add(((Object) (new Artifact(161, "Erivagil", 1, 0, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(162, "Glosovagil", 1, 0, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(163, "Mirror of Galadriel", 1, 2, "+40 Mage,Scry Area"))));
        artifacts.add(((Object) (new Artifact(164, "Tintelp\353", 1, 2, "+1750 Combat"))));
        artifacts.add(((Object) (new Artifact(165, "Cuiviegurth", 1, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(166, "Calris", 1, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(167, "Aedring", 1, 2, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(168, "Ancaruin", 1, 2, "+2250 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(169, "Gurthang", 1, 1, "+2250 Combat,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(170, "Anguirel", 1, 0, "+2250 Combat,Dark Summons List"))));
        artifacts.add(((Object) (new Artifact(171, "Aracu", 1, 2, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(172, "Axe of Braogha", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(173, "Daecollo", 1, 0, "+20 Stealth"))));
        artifacts.add(((Object) (new Artifact(174, "Belthronding", 1, 2, "+2250 Combat"))));
        artifacts.add(((Object) (new Artifact(175, "Ring of Curufin", 1, 0, "+30 Agent"))));
        artifacts.add(((Object) (new Artifact(176, "Spear of Bladorthin", 1, 0, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(177, "Calninqu\353", 1, 2, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(178, "Cubeleg", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(179, "Durcarak", 1, 1, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(180, "Fuinrauko", 1, 1, "+2000 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(181, "Herugrim", 1, 2, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(182, "Morgurth", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(183, "Silmaruth", 1, 0, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(184, "Stone Mace of Setmaenen", 1, 2, "+500 Combat,Bonus vs Undead"))));
        artifacts.add(((Object) (new Artifact(185, "Headband of Slaeg", 1, 0, "+10 Mage,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(186, "Sceptre of Hent", 1, 2, "+500 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(187, "The Black Book", 1, 0, "+10 Mage,Teleport"))));
        artifacts.add(((Object) (new Artifact(188, "E Mere Vardo", 1, 2, "+10 Mage,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(189, "Blue Ring", 1, 1, "+10 Mage,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(190, "Staff of the Wanderer", 1, 2, "+15 Mage,Teleport"))));
        artifacts.add(((Object) (new Artifact(191, "Aercrist", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(192, "Maikarama", 1, 2, "+750 Combat,Long Stride"))));
        artifacts.add(((Object) (new Artifact(193, "Raukambar", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(194, "Durlachiel", 1, 2, "+750 Combat,Minor Heal"))));
        artifacts.add(((Object) (new Artifact(195, "Shards of Narsil", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(196, "Mighty Blade", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(197, "Forest-blade", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(198, "Flails of Horseslaying", 1, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(199, "G\372thwin\353", 1, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(200, "Mace of the Huntsman", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(201, "R\372nya", 1, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(202, "Sword of Cleaving", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(203, "Spear of Following", 1, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(204, "Steward's Blade", 1, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(205, "Sulhelka", 1, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(206, "Foam-light", 1, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(207, "G\372lthalion", 1, 0, "+30 Command"))));
        artifacts.add(((Object) (new Artifact(208, "Horse-Lord's Shield", 1, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(209, "Rat Gauntlets", 1, 0, "+15 Agent"))));
        artifacts.add(((Object) (new Artifact(210, "Boots of Iron", 1, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(211, "Cloak of Protection", 1, 0, "+10 Agent"))));
        artifacts.add(((Object) (new Artifact(212, "Cloak of Hiding", 1, 0, "+10 Stealth"))));
        artifacts.add(((Object) (new Artifact(213, "Cloak of Valacirca", 1, 0, "+10 Stealth"))));
        artifacts.add(((Object) (new Artifact(1, "Ring of Wind", 0, 0, "+40 Agent"))));
        artifacts.add(((Object) (new Artifact(2, "Ring of Stargazing", 0, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(3, "Ring of Iron Magic", 0, 1, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(4, "Ring of Impersonation", 0, 0, "+25 Agent"))));
        artifacts.add(((Object) (new Artifact(5, "Ring of Barahir", 0, 2, "+35 Command,Bonus vs Dragons/Fell Beasts"))));
        artifacts.add(((Object) (new Artifact(6, "Ring of Axardil", 0, 0, "+10 Command,Teleport"))));
        artifacts.add(((Object) (new Artifact(7, "Nazguaga", 0, 1, "+30 Mage,Dark Summons List"))));
        artifacts.add(((Object) (new Artifact(8, "Lorgl\356n", 0, 0, "+15 Mage"))));
        artifacts.add(((Object) (new Artifact(9, "Elenya", 0, 0, "+15 Stealth"))));
        artifacts.add(((Object) (new Artifact(10, "Dwarven Ring of Power", 0, 0, "+40 Command"))));
        artifacts.add(((Object) (new Artifact(11, "Vilya", 0, 0, "+50 Mage"))));
        artifacts.add(((Object) (new Artifact(12, "Nenya", 0, 0, "+50 Mage"))));
        artifacts.add(((Object) (new Artifact(13, "Narya", 0, 0, "+50 Mage"))));
        artifacts.add(((Object) (new Artifact(14, "The One Ring", 0, 0, "+40 Stealth"))));
        artifacts.add(((Object) (new Artifact(15, "Tinculin", 0, 0, "+40 Mage,Spirits Mastery List"))));
        artifacts.add(((Object) (new Artifact(16, "Mothras", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(17, "Horn of Fear", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(18, "Tablets of Dark Knowledge", 0, 1, "+15 Mage,Random Lost List"))));
        artifacts.add(((Object) (new Artifact(19, "Staff of Storms", 0, 0, "Open Seas,Dark Summons List"))));
        artifacts.add(((Object) (new Artifact(20, "Staff of the Serpent", 0, 0, "+10 Mage"))));
        artifacts.add(((Object) (new Artifact(21, "Staff of Earthmastery", 0, 0, "+20 Mage,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(22, "Rauzgnagli", 0, 1, "+1750 Combat"))));
        artifacts.add(((Object) (new Artifact(23, "Nedelhach", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(24, "Ghostbane", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(25, "Staff of Bronze", 0, 0, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(26, "Mallorn Staff", 0, 0, "+25 Mage"))));
        artifacts.add(((Object) (new Artifact(27, "Palantir of Osgiliath", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(28, "Palantir of Minas Ithil", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(29, "Palantir of Minas Arbir", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(30, "Palantir of Orthanc", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(31, "Palant\355r of Ann\372minas", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(32, "Palantir of Elostirion", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(33, "Palant\355r of Amon S\373l", 0, 0, "Scry Area"))));
        artifacts.add(((Object) (new Artifact(34, "Orb of Dark Seeing", 0, 1, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(35, "Orb of Seeing", 0, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(36, "Suimbalmynas", 0, 0, "+20 Mage,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(37, "Voice of the Dark Tower", 0, 1, "+20 Emissary"))));
        artifacts.add(((Object) (new Artifact(38, "Silver Rod of Ad\372ni", 0, 2, "+25 Command"))));
        artifacts.add(((Object) (new Artifact(39, "Miramarth", 0, 1, "+15 Agent"))));
        artifacts.add(((Object) (new Artifact(40, "Gaergil", 0, 0, "Open Seas"))));
        artifacts.add(((Object) (new Artifact(41, "Mantle of Doriath", 0, 2, "Hide Pop Center"))));
        artifacts.add(((Object) (new Artifact(42, "Collar of Might", 0, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(43, "Cloak of the Heavens", 0, 0, "+15 Agent"))));
        artifacts.add(((Object) (new Artifact(44, "Collohwesta", 0, 0, "+25 Stealth"))));
        artifacts.add(((Object) (new Artifact(45, "Cloak of the Abyss", 0, 0, "+40 Stealth"))));
        artifacts.add(((Object) (new Artifact(46, "Robes of the Orc Priests", 0, 1, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(47, "Belt of Durin", 0, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(48, "Th\364logaer Ciryatano", 0, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(49, "Shield of An\341rion", 0, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(50, "Ovir Crown", 0, 0, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(51, "Ossanna", 0, 0, "+10 Mage"))));
        artifacts.add(((Object) (new Artifact(52, "Morgul Plate", 0, 1, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(53, "Listening Helm", 0, 0, "+10 Agent"))));
        artifacts.add(((Object) (new Artifact(54, "Helm of Sen Jay", 0, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(55, "Helm of Shadow", 0, 0, "+10 Stealth"))));
        artifacts.add(((Object) (new Artifact(56, "Helm of the Mumak-King", 0, 0, "+25 Command,Bonus Recruit/Fight Mumaks"))));
        artifacts.add(((Object) (new Artifact(57, "Helm of Isildur", 0, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(58, "Helm of the Dark", 0, 1, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(59, "Gaerennon", 0, 0, "+20 Command"))));
        artifacts.add(((Object) (new Artifact(60, "Durin's Armor and Shield", 0, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(61, "Dragon Helm of Dor-L\363min", 0, 0, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(62, "Dragon Helm and Armor", 0, 1, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(63, "Cu-Saggha-brath", 0, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(64, "Bracers of the Mist", 0, 0, "+30 Stealth"))));
        artifacts.add(((Object) (new Artifact(65, "Angbor", 0, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(66, "Bracers of Chennacatt", 0, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(67, "Ul\373kai", 0, 1, "+30 Command"))));
        artifacts.add(((Object) (new Artifact(68, "Thrakurghash", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(69, "Erchmar", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(70, "Ring of Binding", 0, 1, "+30 Agent"))));
        artifacts.add(((Object) (new Artifact(71, "Talisman of Absorption", 0, 1, "+20 Mage"))));
        artifacts.add(((Object) (new Artifact(72, "Cloak of Duvorn", 0, 0, "+20 Agent"))));
        artifacts.add(((Object) (new Artifact(73, "Yellow Hammer", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(74, "War-dancer", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(75, "Vasamacil", 0, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(76, "Usriev", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(77, "Ungolrist", 0, 2, "+750 Combat,Bonus vs Spiders"))));
        artifacts.add(((Object) (new Artifact(78, "Sword of Soul Reducing", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(79, "Stormless Bow", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(80, "Snow Hammer", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(81, "Sil-Maegil", 0, 2, "+750 Combat,Bonus vs Evil Creatures"))));
        artifacts.add(((Object) (new Artifact(82, "Romoquen\341ro", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(83, "Orcrist", 0, 2, "+2250 Combat"))));
        artifacts.add(((Object) (new Artifact(84, "Ongrum", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(85, "Navron", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(86, "Nallagurth", 0, 1, "+750 Combat,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(87, "Morlhach", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(88, "Macirill\353", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(89, "Macilr\363men", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(90, "Helkaluin", 0, 0, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(91, "Gordur", 0, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(92, "Horse-Tamer", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(93, "Gurthdur", 0, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(94, "Glamdring", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(95, "Gildagor", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(96, "Fohnrad", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(97, "Fire's Edge", 0, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(98, "Elhach", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(99, "Elfhewer", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(100, "Elfbane", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(101, "E Voronw\353", 0, 2, "+500 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(102, "Durin's Axe", 0, 0, "+750 Combat,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(103, "Durcrist", 0, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(104, "Dawnsword", 0, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(105, "Culok", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(106, "Cubragol", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(107, "Curaran", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(108, "Craig-olf-Ti", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(109, "Cloud Bow", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(110, "Cirmegil", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(111, "Believer's Bane", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(112, "Burning Blade", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(113, "Ar-sil", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(114, "Angian", 0, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(115, "Fire Mace", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(116, "Blood Spike", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(117, "Hatred Curse", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(118, "Skull Flail", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(119, "Moon-Axe", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(120, "Hammer of the Deeps", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(121, "Troll Slayer", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(122, "Orc Slayer", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(123, "Amulet of Communing", 0, 0, "+15 Mage"))));
        artifacts.add(((Object) (new Artifact(124, "Herufe\344", 0, 0, "+10 Command"))));
        artifacts.add(((Object) (new Artifact(125, "Aeglin", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(126, "Anarmacil", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(127, "Aranr\373th", 0, 2, "+1750 Combat,Bonus vs Evil Creatures"))));
        artifacts.add(((Object) (new Artifact(128, "Aratocam", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(129, "Bow of Thunder and Bone", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(130, "Br\364dic Spear", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(131, "Caranlhach", 0, 0, "+1750 Combat"))));
        artifacts.add(((Object) (new Artifact(132, "Daeron's Rapier", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(133, "Dagger of Green Wisdom", 0, 0, "+500 Combat,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(134, "Dagnirdraug", 0, 2, "+750 Combat,Bonus vs Wolves"))));
        artifacts.add(((Object) (new Artifact(135, "Elenr\373th", 0, 0, "+750 Combat,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(136, "Foam Cleaver", 0, 0, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(137, "Bloodrunner", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(138, "Air-cleaver", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(139, "Gersebroc", 0, 2, "+750 Combat,Bonus vs Dragons/Fell Beasts"))));
        artifacts.add(((Object) (new Artifact(140, "Hammer of Returning", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(141, "Hue Changer", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(142, "Kirrauko", 0, 2, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(143, "Night-piercer", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(144, "Orcring", 0, 2, "+2250 Combat"))));
        artifacts.add(((Object) (new Artifact(145, "Orcruin", 0, 2, "+2250 Combat"))));
        artifacts.add(((Object) (new Artifact(146, "Horse-slayer", 0, 0, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(147, "Ringil", 0, 2, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(148, "Sickle of the Heavens", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(149, "Sting", 0, 2, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(150, "Stinging Tongue", 0, 1, "+500 Combat"))));
        artifacts.add(((Object) (new Artifact(151, "Troll-Cleaver", 0, 2, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(152, "Turantir", 0, 2, "+500 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(153, "Water-skimmer", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(154, "Ring of Bleeding", 0, 1, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(155, "Taurin", 0, 0, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(156, "Maranya", 0, 0, "+30 Mage"))));
        artifacts.add(((Object) (new Artifact(157, "Pectoral", 0, 0, "+30 Emissary"))));
        artifacts.add(((Object) (new Artifact(158, "Thunder's Edge", 0, 1, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(159, "Skull Helm", 0, 1, "+15 Command"))));
        artifacts.add(((Object) (new Artifact(160, "Collar of Command", 0, 0, "+30 Command"))));
        artifacts.add(((Object) (new Artifact(161, "Erivagil", 0, 0, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(162, "Glosovagil", 0, 0, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(163, "Mirror of Galadriel", 0, 2, "+40 Mage,Scout Area"))));
        artifacts.add(((Object) (new Artifact(164, "Tintelp\353", 0, 2, "+1750 Combat"))));
        artifacts.add(((Object) (new Artifact(165, "Cuiviegurth", 0, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(166, "Calris", 0, 1, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(167, "Aedring", 0, 2, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(168, "Ancaruin", 0, 2, "+2250 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(169, "Gurthang", 0, 1, "+2250 Combat,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(170, "Anguirel", 0, 0, "+2250 Combat,Dark Summons List"))));
        artifacts.add(((Object) (new Artifact(171, "Aracu", 0, 2, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(172, "Axe of Braogha", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(173, "Hammer of Balli", 0, 2, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(174, "Belthronding", 0, 2, "+2250 Combat"))));
        artifacts.add(((Object) (new Artifact(175, "Ring of Curufin", 0, 0, "+30 Agent"))));
        artifacts.add(((Object) (new Artifact(176, "Spear of Bladorthin", 0, 0, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(177, "Calninqu\353", 0, 2, "+1500 Combat"))));
        artifacts.add(((Object) (new Artifact(178, "Cubeleg", 0, 0, "+750 Combat"))));
        artifacts.add(((Object) (new Artifact(179, "Durcarak", 0, 1, "+1250 Combat"))));
        artifacts.add(((Object) (new Artifact(180, "Fuinrauko", 0, 1, "+2000 Combat,Teleport"))));
        artifacts.add(((Object) (new Artifact(181, "Herugrim", 0, 2, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(182, "Morgurth", 0, 0, "+1000 Combat"))));
        artifacts.add(((Object) (new Artifact(183, "Silmaruth", 0, 0, "+2000 Combat"))));
        artifacts.add(((Object) (new Artifact(184, "Stone Mace of Setmaenen", 0, 2, "+500 Combat,Bonus vs Undead"))));
        artifacts.add(((Object) (new Artifact(185, "Headband of Slaeg", 0, 0, "+10 Mage,Conjuring Ways List"))));
        artifacts.add(((Object) (new Artifact(186, "Sceptre of Hent", 0, 2, "+750 Combat,Bonus vs Wolves"))));
        artifacts.add(((Object) (new Artifact(187, "The Black Book", 0, 0, "+10 Mage,Teleport"))));
        artifacts.add(((Object) (new Artifact(188, "E Mere Vardo", 0, 2, "+10 Mage,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(189, "Blue Ring", 0, 1, "+10 Mage,Spirit Mastery List"))));
        artifacts.add(((Object) (new Artifact(190, "Staff of the Wanderer", 0, 0, "+15 Mage,Teleport"))));
    }
}
