// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) braces fieldsfirst safe
// Source File Name:   java

package com.middleearthgames.orderchecker;

import java.util.Vector;

// Referenced classes of package com.middleearthgames.orderchecker:
//            Artifact, Main

public class ArtifactList
{

	public final static int GAME_PBM = 0;
	public final static int GAME_WTR = 1;
    private Vector artifacts;

    public Vector getArtifacts() {
    	return this.artifacts;
    }
    ArtifactList()
    {
        this.artifacts = new Vector();
        configureList();
    }

    Artifact findArtifact(int artifactNum)
    {
        int gameType = Main.main.getData().getGameType();
/*        if(gameType != 1 && gameType != 0)
        {
            return null;
        }
*/        for(int i = 0; i < this.artifacts.size(); i++)
        {
            Artifact artifact = (Artifact)this.artifacts.get(i);
            if(artifact.getArtifactNumber() == artifactNum && artifact.getGame() == gameType)
            {
                return artifact;
            }
        }

        return null;
    }

    private void configureList()
    {
        this.artifacts.add(((Object) (new Artifact(1, "Ring of Wind", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+40 Agent"))));
        this.artifacts.add(((Object) (new Artifact(2, "Ring of Stargazing", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+25 Mage"))));
        this.artifacts.add(((Object) (new Artifact(3, "Ring of Iron Magic", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(4, "Ring of Impersonation", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+25 Agent"))));
        this.artifacts.add(((Object) (new Artifact(5, "Ring of Barahir", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+35 Command"))));
        this.artifacts.add(((Object) (new Artifact(6, "Ring of Axardil", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Command,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(7, "Nazgauga", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+30 Mage,Allows learning of Dark Summons spells"))));
        this.artifacts.add(((Object) (new Artifact(8, "Lorgl\356n", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Mage"))));
        this.artifacts.add(((Object) (new Artifact(9, "Elenya", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(10, "W\364lor Priest Ring", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(11, "Vilya", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+50 Mage"))));
        this.artifacts.add(((Object) (new Artifact(12, "Nenya", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+50 Mage"))));
        this.artifacts.add(((Object) (new Artifact(13, "Narya", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+50 Mage"))));
        this.artifacts.add(((Object) (new Artifact(14, "The One Ring", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+40 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(15, "Tinculin", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+40 Mage,Allows learning of Spirit Mastery spells"))));
        this.artifacts.add(((Object) (new Artifact(16, "Mothras", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat,Allows learning of Conjuring Ways spells"))));
        this.artifacts.add(((Object) (new Artifact(17, "Ring of Angrenost", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(18, "Tablets of Dark Knowledge", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+15 Mage,Allows learning of Dark Summons spells"))));
        this.artifacts.add(((Object) (new Artifact(19, "Staff of Storms", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Open Seas"))));
        this.artifacts.add(((Object) (new Artifact(20, "Staff of the Serpent", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage"))));
        this.artifacts.add(((Object) (new Artifact(21, "Staff of Earthmastery", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage,Allows learning of Conjuring Ways spells"))));
        this.artifacts.add(((Object) (new Artifact(22, "Rauzgnagli", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(23, "Neldelhach", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(24, "Ghostbane", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(25, "Staff of Bronze", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(26, "Mallorn Staff", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+25 Mage"))));
        this.artifacts.add(((Object) (new Artifact(27, "Palantir of Osgiliath", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(28, "Palantir of Minas Ithil", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(29, "Palantir of Minas Anor", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(30, "Palantir of Orthanc", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(31, "Palant\355r of Ann\372minas", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(32, "Palantir of Elostirion", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(33, "Palant\355r of Amon S\373l", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(34, "Orb of Dark Seeing", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(35, "Orb of Seeing", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+35 Mage"))));
        this.artifacts.add(((Object) (new Artifact(36, "Bone Ring", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Mage,Allows learning of Conjuring Ways spells"))));
        this.artifacts.add(((Object) (new Artifact(37, "Voice of the Dark Tower", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+20 Emissary"))));
        this.artifacts.add(((Object) (new Artifact(38, "Silver Rod of Ad\372ni", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+25 Command"))));
        this.artifacts.add(((Object) (new Artifact(39, "Miramarth", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+15 Agent"))));
        this.artifacts.add(((Object) (new Artifact(40, "Gaergil", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Open Seas"))));
        this.artifacts.add(((Object) (new Artifact(41, "Mantle of Doriath", GAME_WTR, Artifact.ALIGNMENT_GOOD, "Hide Pop Center"))));
        this.artifacts.add(((Object) (new Artifact(42, "Collar of Might", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(43, "Cloak of the Heavens", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Agent"))));
        this.artifacts.add(((Object) (new Artifact(44, "Collohwesta", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+25 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(45, "Cloak of the Abyss", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+40 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(46, "Robes of the Orc Priests", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(47, "Belt of Durin", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(48, "Th\364logaer Ciryatano", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(49, "Shield of An\341rion", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(50, "Ovir Crown", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Mage"))));
        this.artifacts.add(((Object) (new Artifact(51, "Ossanna", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage"))));
        this.artifacts.add(((Object) (new Artifact(52, "Morgul Plate", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(53, "Listening Helm", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Agent"))));
        this.artifacts.add(((Object) (new Artifact(54, "Helm of Sen Jay", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(55, "Helm of Shadow", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(56, "Helm of the Mumak-King", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+25 Command"))));
        this.artifacts.add(((Object) (new Artifact(57, "Helm of Isildur", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(58, "Helm of the Dark", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(59, "Gaerennon", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(60, "Durin's Armor/Shield", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(61, "Dragon Helm of Dor-L\363min", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(62, "Dragon Helm and Armor", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(63, "Deepwood Bracelet", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage"))));
        this.artifacts.add(((Object) (new Artifact(64, "Bracers of the Mist", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(65, "Angbor", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(66, "Bracers of Chennacatt", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(67, "Ul\373kai", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+35 Command"))));
        this.artifacts.add(((Object) (new Artifact(68, "Thrakurghash", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(69, "Corantir", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage"))));
        this.artifacts.add(((Object) (new Artifact(70, "Ring of Binding", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+25 Agent"))));
        this.artifacts.add(((Object) (new Artifact(71, "Talisman of Absorption", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(72, "Cloak of Duvorn", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Agent"))));
        this.artifacts.add(((Object) (new Artifact(73, "Yellow Hammer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(74, "War-dancer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(75, "Vasamacil", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(76, "Usriev", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(77, "Ungolrist", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(78, "Sword of Soul Reducing", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(79, "Stormless Bow", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(80, "Snow Hammer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(81, "Sil-Maegil", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(82, "Romoquen\341ro", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(83, "Orcrist", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(84, "Ongrum", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(85, "Navorn", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(86, "Nallagurth", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+750 Combat,Allows learning of Spirit Mastery spells"))));
        this.artifacts.add(((Object) (new Artifact(87, "Morlhach", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(88, "Macirill\353", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(89, "Macilr\363men", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(90, "Helkaluine", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(91, "Gordur", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(92, "Horse-tamer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(93, "Gurthdur", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(94, "Glamdring", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(95, "Gildagor", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(96, "Fohnrad", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(97, "Fire's Edge", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(98, "Elhach", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(99, "Elfhewer", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(100, "Elfbane", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(101, "E Voronw\353", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(102, "Durin's Axe", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat,Allows learning of Conjuring Ways spells"))));
        this.artifacts.add(((Object) (new Artifact(103, "Durcrist", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(104, "Dawnsword", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(105, "Culok", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(106, "Cubragol", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(107, "Curaran", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(108, "Craig-olf-Ti", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(109, "Cloud Bow", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(110, "Cirmegil", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(111, "Believer's Bane", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(112, "Burning Blade", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(113, "Ar-sil", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(114, "Angian", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(115, "Fire Mace", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(116, "Blood Spike", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(117, "Hatred Curse", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(118, "Skull Flail", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(119, "Moon-axe", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(120, "Amulet of Sea Mastery", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "Open Seas"))));
        this.artifacts.add(((Object) (new Artifact(121, "Troll Slayer", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(122, "Orc Slayer", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(123, "Wood-shadow", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(124, "Robes of Aman", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+25 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(125, "Aeglin", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(126, "Anarmacil", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(127, "Aranr\373th", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(128, "Aratocam", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(129, "Bow of Thunder and Bone", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(130, "Br\364dic Spear", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(131, "Caranlhach", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(132, "Daeron's Rapier", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(133, "Dagger of Green Wisdom", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(134, "Dagnirdraug", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(135, "Elenr\373th", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat,Allows learning of Spirit Mastery spells"))));
        this.artifacts.add(((Object) (new Artifact(136, "Foam Cleaver", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(137, "Bloodrunner", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(138, "Air-cleaver", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(139, "Gersebroc", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(140, "Red Robes", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(141, "Hue Changer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(142, "Kirrauko", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(143, "Night-piercer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(144, "Orcring", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(145, "Orcruin", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(146, "Horse-slayer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(147, "Ringil", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(148, "Sickle of the Heavens", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(149, "Sting", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(150, "Stinging Tongue", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(151, "Troll-Cleaver", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(152, "Turantir", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(153, "Water-skimmer", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(154, "Ring of Bleeding", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+25 Mage"))));
        this.artifacts.add(((Object) (new Artifact(155, "Taurin", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(156, "Maranya", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(157, "Pectoral", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Emissary"))));
        this.artifacts.add(((Object) (new Artifact(158, "Thunder's Edge", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(159, "Skull Helm", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(160, "Collar of Command", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Command"))));
        this.artifacts.add(((Object) (new Artifact(161, "Erivagil", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(162, "Glosovagil", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(163, "Mirror of Galadriel", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+40 Mage"))));
        this.artifacts.add(((Object) (new Artifact(164, "Tintelp\353", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(165, "Cuiviegurth", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(166, "Calris", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(167, "Aedring", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(168, "Ancaruin", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+2250 Combat,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(169, "Gurthang", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+2250 Combat,Allows learning of Spirit Mastery spells"))));
        this.artifacts.add(((Object) (new Artifact(170, "Anguirel", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+2250 Combat,Allows learning of Dark Summons spells"))));
        this.artifacts.add(((Object) (new Artifact(171, "Aracu", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(172, "Axe of Braogha", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(173, "Daecollo", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(174, "Belthronding", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+2250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(175, "Ring of Curufin", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Agent"))));
        this.artifacts.add(((Object) (new Artifact(176, "Spear of Bladorthin", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(177, "Calninqu\353", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(178, "Cubeleg", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(179, "Durcarak", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(180, "Fuinrauko", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+2000 Combat,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(181, "Herugrim", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(182, "Morgurth", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(183, "Silmaruth", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(184, "Stone Mace of Setmaenen", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(185, "Headband of Slaeg", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage,Allows learning of Conjuring Ways spells"))));
        this.artifacts.add(((Object) (new Artifact(186, "Sceptre of Hent", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(187, "The Black Book", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(188, "E Mere Vardo", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+10 Mage,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(189, "Blue Ring", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+10 Mage,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(190, "Staff of the Wanderer", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+15 Mage,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(191, "Aercrist", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(192, "Maikarama", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(193, "Raukambar", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(194, "Durlachiel", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(195, "Shards of Narsil", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(196, "Mighty Blade", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(197, "Forest-blade", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(198, "Flails of Horseslaying", GAME_WTR, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(199, "G\372thwin\353", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(200, "Mace of the Huntsman", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(201, "R\372nya", GAME_WTR, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(202, "Sword of Cleaving", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(203, "Spear of Following", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(204, "Steward's Blade", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(205, "Sulhelka", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(206, "Foam-light", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(207, "G\372lthalion", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+30 Command"))));
        this.artifacts.add(((Object) (new Artifact(208, "Horse-Lord's Shield", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(209, "Rat Gauntlets", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+15 Agent"))));
        this.artifacts.add(((Object) (new Artifact(210, "Boots of Iron", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(211, "Cloak of Protection", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Agent"))));
        this.artifacts.add(((Object) (new Artifact(212, "Cloak of Hiding", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(213, "Cloak of Valacirca", GAME_WTR, Artifact.ALIGNMENT_NEUTRAL, "+10 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(1, "Ring of Wind", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+40 Agent"))));
        this.artifacts.add(((Object) (new Artifact(2, "Ring of Stargazing", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(3, "Ring of Iron Magic", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(4, "Ring of Impersonation", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+25 Agent"))));
        this.artifacts.add(((Object) (new Artifact(5, "Ring of Barahir", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+35 Command"))));
        this.artifacts.add(((Object) (new Artifact(6, "Ring of Axardil", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Command,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(7, "Nazgauga", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+30 Mage,Allows learning of Dark Summons List"))));
        this.artifacts.add(((Object) (new Artifact(8, "Lorgl\356n", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Mage"))));
        this.artifacts.add(((Object) (new Artifact(9, "Elenya", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(10, "Dwarven Ring of Power", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+40 Command"))));
        this.artifacts.add(((Object) (new Artifact(11, "Vilya", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+50 Mage"))));
        this.artifacts.add(((Object) (new Artifact(12, "Nenya", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+50 Mage"))));
        this.artifacts.add(((Object) (new Artifact(13, "Narya", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+50 Mage"))));
        this.artifacts.add(((Object) (new Artifact(14, "The One Ring", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+40 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(15, "Tinculin", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+40 Mage,Allows learning of Spirits Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(16, "Mothras", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat,Allows learning of Conjuring Ways spells"))));
        this.artifacts.add(((Object) (new Artifact(17, "Horn of Fear", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(18, "Tablets of Dark Knowledge", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+15 Mage,Allows learning of Dark Summons spells"))));
        this.artifacts.add(((Object) (new Artifact(19, "Staff of Storms", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Open Seas"))));
        this.artifacts.add(((Object) (new Artifact(20, "Staff of the Serpent", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage"))));
        this.artifacts.add(((Object) (new Artifact(21, "Staff of Earthmastery", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage,Allows learning of Conjuring Ways List"))));
        this.artifacts.add(((Object) (new Artifact(22, "Rauzgnagli", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(23, "Neldelhach", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(24, "Ghostbane", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(25, "Staff of Bronze", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(26, "Mallorn Staff", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+25 Mage"))));
        this.artifacts.add(((Object) (new Artifact(27, "Palantir of Osgiliath", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(28, "Palantir of Minas Ithil", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(29, "Palantir of Minas Arbir", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(30, "Palantir of Orthanc", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(31, "Palant\355r of Ann\372minas", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(32, "Palantir of Elostirion", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(33, "Palant\355r of Amon S\373l", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Scry Area"))));
        this.artifacts.add(((Object) (new Artifact(34, "Orb of Dark Seeing", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(35, "Orb of Seeing", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(36, "Suimbalmynas", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage,Allows learning of Conjuring Ways List"))));
        this.artifacts.add(((Object) (new Artifact(37, "Voice of the Dark Tower", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+20 Emissary"))));
        this.artifacts.add(((Object) (new Artifact(38, "Silver Rod of Ad\372ni", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+25 Command"))));
        this.artifacts.add(((Object) (new Artifact(39, "Miramarth", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+15 Agent"))));
        this.artifacts.add(((Object) (new Artifact(40, "Gaergil", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "Open Seas"))));
        this.artifacts.add(((Object) (new Artifact(41, "Mantle of Doriath", GAME_PBM, Artifact.ALIGNMENT_GOOD, "Hide Pop Center"))));
        this.artifacts.add(((Object) (new Artifact(42, "Collar of Might", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(43, "Cloak of the Heavens", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Agent"))));
        this.artifacts.add(((Object) (new Artifact(44, "Collohwesta", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+25 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(45, "Cloak of the Abyss", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+40 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(46, "Robes of the Orc Priests", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(47, "Belt of Durin", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(48, "Th\364logaer Ciryatano", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(49, "Shield of An\341rion", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(50, "Ovir Crown", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(51, "Ossanna", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage"))));
        this.artifacts.add(((Object) (new Artifact(52, "Morgul Plate", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(53, "Listening Helm", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Agent"))));
        this.artifacts.add(((Object) (new Artifact(54, "Helm of Sen Jay", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(55, "Helm of Shadow", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(56, "Helm of the Mumak-King", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+25 Command"))));
        this.artifacts.add(((Object) (new Artifact(57, "Helm of Isildur", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(58, "Helm of the Dark", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(59, "Gaerennon", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Command"))));
        this.artifacts.add(((Object) (new Artifact(60, "Durin's Armor/Shield", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(61, "Dragon Helm of Dor-L\363min", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(62, "Dragon Helm and Armor", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(63, "Cu-Saggha-brath", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(64, "Bracers of the Mist", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Stealth"))));
        this.artifacts.add(((Object) (new Artifact(65, "Angbor", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(66, "Bracers of Chennacatt", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(67, "Ul\373kai", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+30 Command"))));
        this.artifacts.add(((Object) (new Artifact(68, "Thrakurghash", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(69, "Erchmar", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(70, "Ring of Binding", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+30 Agent"))));
        this.artifacts.add(((Object) (new Artifact(71, "Talisman of Absorption", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+20 Mage"))));
        this.artifacts.add(((Object) (new Artifact(72, "Cloak of Duvorn", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+20 Agent"))));
        this.artifacts.add(((Object) (new Artifact(73, "Yellow Hammer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(74, "War-dancer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(75, "Vasamacil", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(76, "Usriev", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(77, "Ungolrist", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(78, "Sword of Soul Reducing", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(79, "Stormless Bow", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(80, "Snow Hammer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(81, "Sil-Maegil", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(82, "Romoquen\341ro", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(83, "Orcrist", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(84, "Ongrum", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(85, "Navron", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(86, "Nallagurth", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+750 Combat,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(87, "Morlhach", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(88, "Macirill\353", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(89, "Macilr\363men", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(90, "Helkaluine", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(91, "Gordur", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(92, "Horse-Tamer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(93, "Gurthdur", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(94, "Glamdring", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(95, "Gildagor", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(96, "Fohnrad", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(97, "Fire's Edge", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(98, "Elhach", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(99, "Elfhewer", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(100, "Elfbane", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(101, "E Voronw\353", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(102, "Durin's Axe", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat,Allows learning of Conjuring Ways List"))));
        this.artifacts.add(((Object) (new Artifact(103, "Durcrist", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(104, "Dawnsword", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(105, "Culok", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(106, "Cubragol", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(107, "Curaran", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(108, "Craig-olf-Ti", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(109, "Cloud Bow", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(110, "Cirmegil", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(111, "Believer's Bane", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(112, "Burning Blade", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(113, "Ar-sil", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(114, "Angian", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(115, "Fire Mace", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(116, "Blood Spike", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(117, "Hatred Curse", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(118, "Skull Flail", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(119, "Moon-Axe", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(120, "Hammer of the Deeps", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(121, "Troll Slayer", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(122, "Orc Slayer", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(123, "Amulet of Communing", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Mage"))));
        this.artifacts.add(((Object) (new Artifact(124, "Herufe\344", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Command"))));
        this.artifacts.add(((Object) (new Artifact(125, "Aeglin", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(126, "Anarmacil", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(127, "Aranr\373th", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(128, "Aratocam", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(129, "Bow of Thunder and Bone", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(130, "Br\364dic Spear", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(131, "Caranlhach", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(132, "Daeron's Rapier", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(133, "Dagger of Green Wisdom", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(134, "Dagnirdraug", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(135, "Elenr\373th", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(136, "Foam Cleaver", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(137, "Bloodrunner", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(138, "Air-cleaver", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(139, "Gersebroc", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(140, "Hammer of Returning", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(141, "Hue Changer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(142, "Kirrauko", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(143, "Night-piercer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(144, "Orcring", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(145, "Orcruin", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(146, "Horse-slayer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(147, "Ringil", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(148, "Sickle of the Heavens", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(149, "Sting", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(150, "Stinging Tongue", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(151, "Troll-Cleaver", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(152, "Turantir", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(153, "Water-skimmer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(154, "Ring of Bleeding", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(155, "Taurin", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(156, "Maranya", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Mage"))));
        this.artifacts.add(((Object) (new Artifact(157, "Pectoral", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Emissary"))));
        this.artifacts.add(((Object) (new Artifact(158, "Thunder's Edge", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(159, "Skull Helm", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+15 Command"))));
        this.artifacts.add(((Object) (new Artifact(160, "Collar of Command", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Command"))));
        this.artifacts.add(((Object) (new Artifact(161, "Erivagil", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(162, "Glosovagil", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(163, "Mirror of Galadriel", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+40 Mage"))));
        this.artifacts.add(((Object) (new Artifact(164, "Tintelp\353", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(165, "Cuiviegurth", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(166, "Calris", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(167, "Aedring", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(168, "Ancaruin", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2250 Combat,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(169, "Gurthang", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+2250 Combat,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(170, "Anguirel", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+2250 Combat,Allows learning of Dark Summons List"))));
        this.artifacts.add(((Object) (new Artifact(171, "Aracu", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(172, "Axe of Braogha", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(173, "Hammer of Balli", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(174, "Belthronding", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+2250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(175, "Ring of Curufin", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+30 Agent"))));
        this.artifacts.add(((Object) (new Artifact(176, "Spear of Bladorthin", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(177, "Calninqu\353", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(178, "Cubeleg", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(179, "Durcarak", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+1250 Combat"))));
        this.artifacts.add(((Object) (new Artifact(180, "Fuinrauko", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+2000 Combat,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(181, "Herugrim", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(182, "Morgurth", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+1000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(183, "Silmaruth", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+2000 Combat"))));
        this.artifacts.add(((Object) (new Artifact(184, "Stone Mace of Setmaenen", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+500 Combat"))));
        this.artifacts.add(((Object) (new Artifact(185, "Headband of Slaeg", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage,Allows learning of Conjuring Ways List"))));
        this.artifacts.add(((Object) (new Artifact(186, "Sceptre of Hent", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+750 Combat"))));
        this.artifacts.add(((Object) (new Artifact(187, "The Black Book", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+10 Mage,Allows learning of Teleport"))));
        this.artifacts.add(((Object) (new Artifact(188, "E Mere Vardo", GAME_PBM, Artifact.ALIGNMENT_GOOD, "+10 Mage,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(189, "Blue Ring", GAME_PBM, Artifact.ALIGNMENT_EVIL, "+10 Mage,Allows learning of Spirit Mastery List"))));
        this.artifacts.add(((Object) (new Artifact(190, "Staff of the Wanderer", GAME_PBM, Artifact.ALIGNMENT_NEUTRAL, "+15 Mage,Allows learning of Teleport"))));
    }
}
